//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotesListView
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int NotesID { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
    }
}
